# Generated by Django 4.2.23 on 2025-09-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={},
        ),
    ]
